# Generated by Django 5.1.1 on 2024-09-30 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_applicationuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConversationThreads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=200)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.applicationuser')),
            ],
            options={
                'verbose_name': 'User Conversation Threads',
            },
        ),
    ]
