# Generated by Django 5.1.1 on 2024-09-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationuser',
            options={'verbose_name': 'Application Users'},
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='choice_of_convo_remembering',
            field=models.BooleanField(default=False),
        ),
    ]
